# [TAG_TURBOT_EMBED_PLAN] Generator for src/llama-turbot-default-plan.h: the built-in turbot plan that
# `-ctk turbot -ctv turbot` uses when no --kv-tier-plan and no LLAMA_TURBOT_PLAN is given (or with
# `--kv-tier-plan default`). The header carries docs/turbot/plans/turbot-default.plan verbatim as a C string.
#
# CPU only, stdlib only (no numpy, unlike gen_turbot_tables.py), deterministic.
#
#   python docs/turbot/gen_turbot_default_plan.py            # (re)write src/llama-turbot-default-plan.h
#   python docs/turbot/gen_turbot_default_plan.py --check    # exit 1 if the checked-in header differs from a fresh run
#
# Why a checked-in generated header and not a configure-time file(READ) + configure_file:
#   - the fork is a general llama.cpp that other software vendors. Some of them compile src/*.cpp with their own
#     build system (no CMake configure step, and often no docs/ directory). A checked-in header builds everywhere.
#   - drift is still impossible in a CMake build. src/CMakeLists.txt reads the plan file at configure time, hashes it
#     (SHA-256 of the text with LF line endings) and stops with FATAL_ERROR when LLAMA_TURBOT_DEFAULT_PLAN_SHA256 in
#     the header differs. It also lists both files in CMAKE_CONFIGURE_DEPENDS, so editing the plan re-runs that check
#     on the next build. `--check` here does the same for CI or by hand.
#   - tests/test-turbot.cpp parses llama_turbot_default_plan_text() and checks the plan hash 0x56c3503c949a7749.
#
# Rules:
#   - the embedded text is the plan file with CRLF turned into LF, so every platform compiles the same bytes;
#   - the plan is validated with tools/turbot/turbot_plan.py (the Python mirror of llama_turbot_plan_parse_text) and
#     its plan hash at 262144 cells is written as LLAMA_TURBOT_DEFAULT_PLAN_HASH;
#   - the header is written with the line endings of the plan file on disk (CRLF in a Windows checkout), and --check
#     compares with CR removed, so it gives the same answer in CRLF and LF checkouts.
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
PLAN = os.path.join(ROOT, "docs", "turbot", "plans", "turbot-default.plan")
HEADER = os.path.join(ROOT, "src", "llama-turbot-default-plan.h")
PLAN_REL = "docs/turbot/plans/turbot-default.plan"

sys.dont_write_bytecode = True   # no __pycache__ next to tools/turbot/turbot_plan.py
sys.path.insert(0, os.path.join(ROOT, "tools", "turbot"))
import turbot_plan  # noqa: E402  (tools/turbot/turbot_plan.py, stdlib only)

KV_SIZE = 262144
MSVC_LITERAL_MAX = 65535   # MSVC C2026: a concatenated string literal must stay below 64 KiB

# the model the plan was calibrated on; libllama prints it in the log line and in the "does not fit" error.
# Update it together with the plan.
CALIBRATED_ON = "Qwen3.8-27B"


def c_escape(line):
    out = []
    for ch in line:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\t":
            out.append("\\t")
        elif 0x20 <= o < 0x7F:
            out.append(ch)
        else:
            # octal is never greedy past 3 digits, unlike \x
            for b in ch.encode("utf-8"):
                out.append("\\%03o" % b)
    return "".join(out)


def render(text):
    """text: the plan with LF line endings -> header text with LF line endings."""
    # attn_layers None: every L/Y line is checked, the layer set is whatever the plan names (not tied to one model)
    plan = turbot_plan.parse_text(text, None, KV_SIZE)
    phash = turbot_plan.plan_hash(plan)
    sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
    layers = sorted(plan["layers"])
    if len(text.encode("utf-8")) + 1 >= MSVC_LITERAL_MAX:
        raise SystemExit("ERROR: the plan is %d bytes, too large for one MSVC string literal" % len(text))

    o = []
    o.append("// [TAG_TURBOT_EMBED_PLAN] GENERATED by docs/turbot/gen_turbot_default_plan.py from")
    o.append("// %s - do not edit by hand: edit the plan, then re-run the script." % PLAN_REL)
    o.append("//")
    o.append("// The built-in turbot plan (llama_turbot_default_plan_text, src/llama-kv-tier.cpp). It is used by")
    o.append("// -ctk turbot -ctv turbot when neither --kv-tier-plan nor LLAMA_TURBOT_PLAN is given and it fits the model's")
    o.append("// attention layers, and always with --kv-tier-plan default. Calibrated on Qwen3.8-27B.")
    o.append("//")
    o.append("// Drift guard: src/CMakeLists.txt compares LLAMA_TURBOT_DEFAULT_PLAN_SHA256 with the plan file at configure")
    o.append("// time and stops when they differ; `python docs/turbot/gen_turbot_default_plan.py --check` does the same.")
    o.append("// Only src/llama-kv-tier.cpp includes this header.")
    o.append("#pragma once")
    o.append("")
    o.append("// SHA-256 of the plan text below (the plan file with LF line endings). src/CMakeLists.txt parses this line.")
    o.append('#define LLAMA_TURBOT_DEFAULT_PLAN_SHA256 "%s"' % sha)
    o.append("")
    o.append("// plan hash of the parsed plan when the cache has at least POOL cells (a smaller cache clamps POOL, which")
    o.append("// changes the hash). Same value as tools/turbot/plan_vram.py and the turbot size log line.")
    o.append("#define LLAMA_TURBOT_DEFAULT_PLAN_HASH 0x%016xull" % phash)
    o.append("")
    o.append("// for log lines and errors: where the plan comes from, the model it was calibrated on, its attention layers")
    o.append('#define LLAMA_TURBOT_DEFAULT_PLAN_FILE   "%s"' % PLAN_REL)
    o.append('#define LLAMA_TURBOT_DEFAULT_PLAN_MODEL  "%s"' % c_escape(CALIBRATED_ON))
    o.append('#define LLAMA_TURBOT_DEFAULT_PLAN_LAYERS "%s"' % " ".join(str(il) for il in layers))
    o.append("")
    o.append("// %d attention layers, POOL %d, CAP %d" % (len(layers), plan["pool"], plan["cap"]))
    o.append("static const char LLAMA_TURBOT_DEFAULT_PLAN_TEXT[] =")
    lines = text.split("\n")
    # text ends with "\n" in the normal case, which leaves one empty last element
    if lines and lines[-1] == "":
        lines = lines[:-1]
        body = ['    "%s\\n"' % c_escape(l) for l in lines]
    else:
        body = ['    "%s\\n"' % c_escape(l) for l in lines[:-1]] + ['    "%s"' % c_escape(lines[-1])]
    if not body:
        body = ['    ""']
    body[-1] += ";"
    o += body
    return "\n".join(o) + "\n", phash, sha, layers


def main():
    with open(PLAN, "rb") as f:
        raw = f.read()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as e:
        print("ERROR: %s is not UTF-8: %s" % (PLAN, e))
        return 1
    if text.startswith("\ufeff"):
        print("ERROR: %s starts with a UTF-8 BOM; remove it" % PLAN)
        return 1
    if "\0" in text:
        print("ERROR: %s contains a NUL byte" % PLAN)
        return 1
    text = text.replace("\r\n", "\n")
    try:
        header, phash, sha, layers = render(text)
    except turbot_plan.PlanError as e:
        print("ERROR: %s does not parse: %s" % (PLAN, e))
        return 1

    if "--check" in sys.argv:
        cur = ""
        if os.path.exists(HEADER):
            with open(HEADER, "rb") as f:
                cur = f.read().decode("utf-8", errors="replace").replace("\r", "")
        same = cur == header
        print("llama-turbot-default-plan.h %s" % ("matches" if same else "DIFFERS from a fresh generation"))
        return 0 if same else 1

    eol = "\r\n" if b"\r\n" in raw else "\n"
    with open(HEADER, "wb") as f:
        f.write(header.replace("\n", eol).encode("utf-8"))
    print("wrote %s (plan hash 0x%016x, sha256 %s, %d attention layers)" % (HEADER, phash, sha, len(layers)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
