// [TAG_TURBOT_EMBED_PLAN] GENERATED by docs/turbot/gen_turbot_default_plan.py from
// docs/turbot/plans/turbot-default.plan - do not edit by hand: edit the plan, then re-run the script.
//
// The built-in turbot plan (llama_turbot_default_plan_text, src/llama-kv-tier.cpp). It is used by
// -ctk turbot -ctv turbot when neither --kv-tier-plan nor LLAMA_TURBOT_PLAN is given and it fits the model's
// attention layers, and always with --kv-tier-plan default. Calibrated on Qwen3.8-27B.
//
// Drift guard: src/CMakeLists.txt compares LLAMA_TURBOT_DEFAULT_PLAN_SHA256 with the plan file at configure
// time and stops when they differ; `python docs/turbot/gen_turbot_default_plan.py --check` does the same.
// Only src/llama-kv-tier.cpp includes this header.
#pragma once

// SHA-256 of the plan text below (the plan file with LF line endings). src/CMakeLists.txt parses this line.
#define LLAMA_TURBOT_DEFAULT_PLAN_SHA256 "7ceb6cc2a46f5aa6823f1381e17a6a7dc5f23ca5b7a3d013972411d9e6cec11c"

// plan hash of the parsed plan when the cache has at least POOL cells (a smaller cache clamps POOL, which
// changes the hash). Same value as tools/turbot/plan_vram.py and the turbot size log line.
#define LLAMA_TURBOT_DEFAULT_PLAN_HASH 0x56c3503c949a7749ull

// for log lines and errors: where the plan comes from, the model it was calibrated on, its attention layers
#define LLAMA_TURBOT_DEFAULT_PLAN_FILE   "docs/turbot/plans/turbot-default.plan"
#define LLAMA_TURBOT_DEFAULT_PLAN_MODEL  "Qwen3.8-27B"
#define LLAMA_TURBOT_DEFAULT_PLAN_LAYERS "3 7 11 15 19 23 27 31 35 39 43 47 51 55 59 63"

// 16 attention layers, POOL 65536, CAP 16384
static const char LLAMA_TURBOT_DEFAULT_PLAN_TEXT[] =
    "# turbot default plan: fq_3t0 old widths (E:\\kv-s3\\plans\\fq_3t0_w256_m16384_7b.txt), young width 7 everywhere\n"
    "# base 4520.00 MiB + young pool 726.00 MiB = 5246.00 MiB at 262144 cells (turbo5p 5248.00 MiB)\n"
    "POOL 65536\n"
    "CAP 16384\n"
    "L 3 K 2 2 2 4 V 2 2 2 4\n"
    "L 7 K 2 5 3 2 V 2 5 2 2\n"
    "L 11 K 4 5 4 2 V 3 4 5 2\n"
    "L 15 K 4 4 3 4 V 5 3 3 4\n"
    "L 19 K 4 4 3 4 V 3 4 2 5\n"
    "L 23 K 5 4 4 6 V 5 4 4 5\n"
    "L 27 K 5 5 6 5 V 5 5 6 5\n"
    "L 31 K 6 5 5 5 V 5 4 5 4\n"
    "L 35 K 4 5 5 5 V 4 4 4 5\n"
    "L 39 K 5 5 4 6 V 4 4 4 5\n"
    "L 43 K 4 4 6 5 V 4 4 5 4\n"
    "L 47 K 4 5 5 5 V 4 4 5 5\n"
    "L 51 K 5 5 5 6 V 5 4 4 5\n"
    "L 55 K 5 5 5 5 V 5 5 5 5\n"
    "L 59 K 4 5 5 5 V 5 6 5 5\n"
    "L 63 K 4 4 4 4 V 5 4 5 5\n";
